version: '3.8'

services:
  # Milvus 向量数据库（独立模式）
  milvus:
    image: milvusdb/milvus:v2.3.3
    container_name: hit-rag-milvus
    environment:
      ETCD_USE_EMBED: "true"
      COMMON_STORAGETYPE: local
    volumes:
      - ../volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    restart: unless-stopped

  # 后端 API 服务
  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: hit-rag-backend
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    env_file:
      - ../.env
    volumes:
      - ../:/app
      - ../all-md:/app/all-md
      - ../volumes/output:/app/output
      - ../volumes/db:/app/db
    ports:
      - "8000:8000"
    depends_on:
      milvus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/assistants"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    command: ["uv", "run", "python", "api_server.py"]

  # 前端 UI 服务
  frontend:
    build:
      context: ../hit-rag-ui
      dockerfile: Dockerfile
    container_name: hit-rag-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ../hit-rag-ui:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # versa-chat-view 聊天界面
  chat-view:
    build:
      context: ../versa-chat-view
      dockerfile: Dockerfile
    container_name: hit-rag-chat-view
    environment:
      - RAG_API_BASE=http://localhost:8000
      - NEXT_PUBLIC_WELCOME_TITLE=RAG 智能问答助手
      - NEXT_PUBLIC_WELCOME_MESSAGE=询问关于您文档的任何问题
    volumes:
      - ../versa-chat-view:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: hit-rag-network
